stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps: 
    - src/data_ingestion.py
    outs: 
    - data/raw

  pre_processing:
    cmd: python src/pre-processing.py
    deps:
    - data/raw
    - src/pre-processing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    outs:
    - data/processed
  
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - data/processed
    outs:
    - reports/metrics.json